### ISSUE TITLE
no such table: ldap3_sync_ldapuser

### ISSUE THREAD

**Issue by seanherron** [PGower/django-ldap3-sync#3]
On running `python manage.py syncldap` I receive the following error:

```
django.db.utils.OperationalError: no such table: ldap3_sync_ldapuser
```

I've run migrations but that doesn't fix the issue.

**Comment by andebor** [comment]
There should probably be a step in the readme telling you to run `python manage.py migrate` before you run `python manage.py syncldap`. That solved the same problem for me.

**Comment by PGower** [comment]
Will add that step now.

**Comment by claudekenni** [comment]
I got the same problem.
The migration does not create any table like that.

**Comment by alexbarcelo** [comment]
There is no `migrations` folder, so `migrate` does not work. I assume that this worked in previous versions of Django, but it does not work in my setup (Python 3.5 & Django 1.9.8) and I assume it won't work in any recent version of Django (1.9, maybe 1.8 also?).

Maybe this issue could be reopened?

[Sometimes I horribly mess things up, so take with a grain of salt, I may be wrong in my assumptions]

**Comment by alexbarcelo** [comment]
As I feared, I am quite wrong. By default, if there are no migrations, the stuff doesn't work. But you can force the migrations to appear by doing a `./manage.py makemigrations ldap3_sync`. Maybe this is enough? (But then should be added to the docs).

Having the `migrations` folder helps if there are future changes on the models for the newer versions of Django (that's what I understood when I learnt them) but I will wait for someone more knowleadgeable check / correct this assumption ;)
